### ISSUE TITLE
Milestone 4a: successfully set up tensorflow ML platform and modify the model

### ISSUE THREAD

**Issue by shospital** [polarwatch/internship24#12]
- [x] replicate (or run) the codes with already processed data from the repository 
- [x] study the LSTM/Attention model and data processing workflow of the journal article
- [x] select a variable from PolarWatch and reformat them for the models (sea ice thickness)
- [x] run the LSTM model with the new variables

**Comment by shospital** [comment]
```TypeError: Exception encountered when calling Functional.call().

Attention.__call__() got multiple values for argument 'training'

Arguments received by Functional.call():
  • inputs=tf.Tensor(shape=(None, 1, 11), dtype=float32)
  • training=True
  • mask=None
```

@tntly it seems like the tensorflow functional() is causing the error.   The argument being passed to tensorflow from Attention conflicts with already existing argument.  I looked at few stackflow and some says uninstall and reinstall tensorflow. I will try to see if i can uninstall it and still get the same issue

**Comment by shospital** [comment]
Sincne Attention.__call_() returns training argument that conflicts, let's not use Attention module and use Attention module from tensorflow.kearas.layer

the original is 

```
from tensorflow.keras.layers import Dense, LSTM

model_input = Input(shape=(timestep,features))
x = LSTM(64, return_sequences=True)(model_input)
x = Dropout(0.2)(x)
x = LSTM(32, return_sequences=True)(x)
x = LSTM(16, return_sequences=True)(x)
x = LSTM(16, return_sequences=True)(x)
x = Attention(trainable = True)(x)
x = Dropout(0.2)(x)
x = Dense(32)(x)
x = Dense(16)(x)
x = Dense(1)(x)
model = Model(model_input, x)
#model.compile(loss='mae', optimizer='adam')
print(model.summary())
```
__modified__ code is 

```
from tensorflow.keras.layers import Dense, LSTM, Attention, Flatten, Concatenate

model_input = Input(shape=(timestep,features))
x = LSTM(64, return_sequences=True)(model_input)
x = Dropout(0.2)(x)
x = LSTM(32, return_sequences=True)(x)
x = LSTM(16, return_sequences=True)(x)
x = LSTM(16, return_sequences=True)(x)

# add attention layer
attention = Attention()([x, x])

# combining LSTM output x with attention output along feature dimension
context_vector = Concatenate(axis=-1)([x, attention])
flattened_context = Flatten()(context_vector)
x = Dropout(0.2)(flattened_context)
x = Dense(32)(x)
x = Dense(16)(x)
x = Dense(1)(x)
model = Model(model_input, x)
#model.compile(loss='mae', optimizer='adam')
print(model.summary())

``
